"""create spots table

Revision ID: 15d7b7613feb
Revises: ffdc0a98111c
Create Date: 2022-02-15 15:13:06.601176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d7b7613feb'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=1000), nullable=False),
    sa.Column('pets', sa.Boolean(), nullable=False),
    sa.Column('total_occupancy', sa.Integer(), nullable=False),
    sa.Column('total_bedrooms', sa.Integer(), nullable=False),
    sa.Column('total_bathrooms', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('has_wifi', sa.Boolean(), nullable=False),
    sa.Column('has_tv', sa.Boolean(), nullable=False),
    sa.Column('has_heat', sa.Boolean(), nullable=False),
    sa.Column('has_ac', sa.Boolean(), nullable=False),
    sa.Column('price_per_day', sa.Float(precision=6, decimal_return_scale=2), nullable=False),
    sa.Column('latitude', sa.String(length=255), nullable=False),
    sa.Column('longitude', sa.String(length=255), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spots')
    # ### end Alembic commands ###
