"""create images table

Revision ID: 16598d0edcff
Revises: 15d7b7613feb
Create Date: 2022-02-15 15:25:22.992170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16598d0edcff'
down_revision = '15d7b7613feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
