"""added longitude and latitude columns.

Revision ID: bd48147cf648
Revises: 97a144b01bfd
Create Date: 2023-06-06 12:40:14.552136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd48147cf648'
down_revision = '97a144b01bfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False))
    op.add_column('spots', sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spots', 'latitude')
    op.drop_column('spots', 'longitude')
    # ### end Alembic commands ###
